[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fac"
dynamic = ["version", "dependencies"]

[project.scripts]
fac = "fac.__main__:main"
facd = "facd.__main__:main"

[tool.setuptools.packages.find]
include = ["fac", "fac.*", "facd"]

[tool.setuptools.package-data]
fac = ["templates/*", "static/*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools_scm]
version_file = "fac/_version.py"
local_scheme = "node-and-timestamp"
